### ISSUE TITLE
Add compile time dependencies

### ISSUE THREAD

**Issue by mrolli** [hpc-unibe-ch/puppet-module-slurm#1]
**Is your feature request related to a current shortcoming? Please describe.**
Currently only packages are installed that are needed to run the daemons. As we compile Slurm
ourselves the compile time dependencies have to installable.

What are the compile deps? Shall we install these on the slurmmaster testserver only? RFC

**Describe the solution you'd like**
Add parameter slurm::compile_deps to have slurm::common::install the compile time dependencies.

**Comment by nfaerber** [comment]
Build dependencies:
rpm-build
gcc
openssl
openssl-devel
pam-devel
numactl
numactl-devel
hwloc
hwloc-devel
lua
lua-devel
readline-devel
rrdtool-devel
ncurses-devel
gtk2-devel
libibmad
libibumad
perl-Switch
perl-ExtUtils-MakeMaker
xorg-x11-xauth
libssh2-devel
man2html
munge
munge-libs
munge-devel
http-parser-devel
json-c-devel
mariadb-server
mariadb-devel
gtk2.x86_64
gtk2-devel.x86_64

**Comment by mrolli** [comment]
Trimmed the list down for mostly debug packages only. Let's if this is sufficient.

The "feature" has not been added to the slurm module but the controlrepo. Reasoning:
The list of dependencies is something that is likely to change and especially dependent on the slurm version that gets installed. At first it seemed a viable option to add a parameter build_deps to the module to be able to provide an array of packages to install alongside the slurm packages, bu then again why bother at all in the module as the module itself does not care about compile/building in it's current form.

The "solutions" is to have a manifest `profile::slurm::build_deps` that does the installation of the build-time dependencies and can be included on every machine one wants, even without installing anything slirm, i.e. on a build host.

See hpc-unibe-ch/ubelix-controlrepo#46 for the respective commit.
